travis:
  secure:
    BINSTAR_TOKEN: P4bRDe1Pw+/Za7nGQgyVIq3MrA0ZrdyT1rQTO7WU2rRQlt8zyXOm0DgaQS/sp3i49irPeoZIv8Qyqfq8fTMT8aFU6qECg7wZpf+Eg09DLtZukGheoUydbJzqdwj/TVqN5v1ii6X1345ksHW6cPIURM1bhzZPUwnhlPZjUlOw+sroiA55DtXyL+GcPSiK7tFro8VLJarZ82f7RENZ3JkEtQKTspoW+ipIknAe/bGAgiRmmM83nx9JZdHeIAut8zj0nNzMCLYVn2dzh+4nSaqr9iCBTs5XZU+a8RUKa45q3vG3eC5XJaj/sP0owqtEglD0/X8yFTeKKH0NGtfFNIdTZM2lQPsDRGEF4trjol1WjLBHP2zwtOeAShRg17aFr/LNMfOXyqtZ5ZVnBczRGMnHJTRIIk3j6lClJ/RnOWQk69+gEuH8Ri3LX6ZF0THa43jifY9FMnzCskx8WKQFAnmtIcHmh60ekAAWMFmuniYSV83GNgM2HAhoTdfWt3VzhevLhViEsoPgkW1kt2DzaCmbRgCZ4Q1zDJKD02KTuWpXhuaOlKNSBE7GtsoHPdjPLNaY2qKA1uiw5xFKaO/XUjUgakws570k1tANKbIH17JvnaOocQGIBCV1ikc8vXdcf+WtuQMOnOvYYbbIbHCJGYgjVOTGk0DBpZmLUA/OTxlf33M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
