travis:
  secure:
    BINSTAR_TOKEN: IcjM7TqtVDf2Bt86wwBxhO6ZN6HMzyIZiTsiw5FHeIUIJ2euIPHZCRzxHAVOXCNm0QE3mdakb14KYHofxD5SzGaen30gn7jcV5aVuIo5vcd2QwPM+cvduHEOn9CJcfoWCCM8g5/0G/slD1GwEgCkTEIHQSCTwuXS4vrvM9Wf2PLBqxxhWb9/AfL3AiqycF4pnG45fGlBs2Bwa/AewxfWH5Ww8EIGsxYBBNMb9VsdY04hPJD4tS/stUcsB3Ti/OCyv+9onzG9CaKH+a7jmaIkdh6EMNyWPs0LxUnHRyyVKHe02rzlOtVZQr8tZhKgI4lmOpJtRHM43hGa/EGKwyFEg8u9RDBWoqWF6pQ5uGuYUozNeXzX0OkxBKDNNSzH4VZsRjlWEk74Hb/X93SoYsdaoZv9mZMTx9A9nZ5QuPkspLJIobB3gGZzwXYjYz16LjDI3QL13R7UhAr/ousNXpXMaJaLrjPclxqVmdlLuuOk1Kw8bhF4kepq/Jsy8Gn1qewq/0U4XndzM/YDZKtlVbD4hAO455nm+G7Ci12mrNBKRF8PpEoOzdpcffY5IqWvASBVODhC4B7QxQIGNEzIGcn2+0sK+cCVcSCDGh70a71NYtwV3KRSnonY7DgovVRp6WoTi6UJQez2TLDvcu0euaQzbYwuNCuNo8NJCzu3VpQfPnk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
